export const POPULARCITIES_LOADING = 'POPULARCITIES_LOADING'
export const POPULARCITIES_SUCCESS = 'POPULARCITIES_SUCCESS'
export const POPULARCITIES_FAILED = 'POPULARCITIES_FAILED'

export const POPULAR_AIRLINES_LOADING = 'POPULAR_AIRLINES_LOADING'
export const POPULAR_AIRLINES_SUCCESS = 'POPULAR_AIRLINES_SUCCESS'
export const POPULAR_AIRLINES_FAILED = 'POPULAR_AIRLINES_FAILED'

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED'
export const USER_SIGNIN_CLEAR = 'USER_SIGNIN_CLEAR'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'
export const USER_REGISTER_CLEAR = 'USER_REGISTER_CLEAR'

export const USER_REQUEST_START = 'USER_REQUEST_START'
export const USER_REQUEST_FAILED = 'USER_REQUEST_FAILED'
export const USER_FETCH = 'USER_FETCH'
export const USER_DELETE = 'USER_DELETE'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_UPDATE_RED = 'USER_UPDATE_RED'

export const CONTACT_US_REQUEST = 'CONTACT_US_REQUEST'
export const CONTACT_US_SUCCESS = 'CONTACT_US_SUCCESS'
export const CONTACT_US_FAILED = 'CONTACT_US_FAILED'

export const FETCH_MESSAGE_REQ = 'FETCH_MESSAGE_REQ'
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS'
export const FETCH_MESSAGE_FAILED = 'FETCH_MESSAGE_FAILED'
